-- src/main/resources/db/migration/V2__insert_initial_data.sql

-- Este script insere os dados iniciais das habilidades da BNCC.
-- Ele deve ser executado após a criação da tabela 'habilidades'.

-- EDUCAÇÃO INFANTIL
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Educação Infantil', 'EI03CO01', 'Reconhecer padrão de repetição em sequência de sons, movimentos, desenhos.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Educação Infantil', 'EI03CO02', 'Expressar as etapas para a realização de uma tarefa de forma clara e ordenada.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Educação Infantil', 'EI03CO03', 'Experienciar a execução de algoritmos brincando com objetos (des)plugados.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Educação Infantil', 'EI03CO04', 'Criar e representar algoritmos para resolver problemas.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Educação Infantil', 'EI03CO05', 'Comparar soluções algorítmicas para resolver um mesmo problema.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Educação Infantil', 'EI03CO06', 'Compreender decisões em dois estados (verdadeiro ou falso).');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Educação Infantil', 'EI03CO07', 'Reconhecer dispositivos eletrônicos (e não-eletrônicos), identificando quando estão ligados ou desligados (abertos ou fechados).');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Educação Infantil', 'EI03CO08', 'Compreender o conceito de interfaces para comunicação com objetos (des)plugados.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Educação Infantil', 'EI03CO09', 'Identificar dispositivos computacionais e as diferentes formas de interação.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Educação Infantil', 'EI03CO10', 'Utilizar tecnologia digital de maneira segura, consciente e respeitosa.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Educação Infantil', 'EI03CO11', 'Adotar hábitos saudáveis de uso de artefatos computacionais, seguindo recomendações de órgãos de saúde competentes.');

-- ENSINO FUNDAMENTAL I - 1º ANO
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 1º Ano', 'EF01CO01', 'Organizar objetos físicos ou digitais considerando diferentes características para esta organização, explicitando semelhanças (padrões) e diferenças.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 1º Ano', 'EF01CO02', 'Identificar e seguir sequências de passos aplicados no dia a dia para resolver problemas.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 1º Ano', 'EF01CO03', 'Reorganizar e criar sequências de passos em meios físicos ou digitais, relacionando essas sequências à palavra ''Algoritmos''.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 1º Ano', 'EF01CO04', 'Reconhecer o que é a informação, que ela pode ser armazenada, transmitida como mensagem por diversos meios e descrita em várias linguagens.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 1º Ano', 'EF01CO05', 'Representar informação usando diferentes codificações.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 1º Ano', 'EF01CO06', 'Reconhecer e explorar artefatos computacionais voltados a atender necessidades pessoais ou coletivas.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 1º Ano', 'EF01CO07', 'Conhecer as possibilidades de uso seguro das tecnologias computacionais para proteção dos dados pessoais e para garantir a própria segurança.');

-- ENSINO FUNDAMENTAL I - 2º ANO
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 2º Ano', 'EF02CO01', 'Criar e comparar modelos (representações) de objetos, identificando padrões e atributos essenciais.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 2º Ano', 'EF02CO02', 'Criar e simular algoritmos representados em linguagem oral, escrita ou pictográfica, construídos como sequências com repetições simples (iterações definidas) com base em instruções preestabelecidas ou criadas, analisando como a precisão da instrução impacta na execução do algoritmo.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 2º Ano', 'EF02CO03', 'Identificar que máquinas diferentes executam conjuntos próprios de instruções e que podem ser usadas para definir algoritmos.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 2º Ano', 'EF02CO04', 'Diferenciar componentes físicos (hardware) e programas que fornecem as instruções (software) para o hardware.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 2º Ano', 'EF02CO05', 'Reconhecer as características e usos das tecnologias computacionais no cotidiano dentro e fora da escola.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 2º Ano', 'EF02CO06', 'Reconhecer os cuidados com a segurança no uso de dispositivos computacionais.');

-- ENSINO FUNDAMENTAL I - 3º ANO
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 3º Ano', 'EF03CO01', 'Associar os valores ''verdadeiro'' e ''falso'' a sentenças lógicas que dizem respeito a situações do dia a dia, fazendo uso de termos que indicam negação.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 3º Ano', 'EF03CO02', 'Criar e simular algoritmos representados em linguagem oral, escrita ou pictográfica, que incluam sequências e repetições simples com condição (iterações indefinidas), para resolver problemas de forma independente e em colaboração.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 3º Ano', 'EF03CO03', 'Aplicar a estratégia de decomposição para resolver problemas complexos, dividindo esse problema em partes menores, resolvendo-as e combinando suas soluções.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 3º Ano', 'EF03CO04', 'Relacionar o conceito de informação com o de dado.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 3º Ano', 'EF03CO05', 'Compreender que dados são estruturados em formatos específicos dependendo da informação armazenada.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 3º Ano', 'EF03CO06', 'Reconhecer que, para um computador realizar tarefas, ele se comunica com o mundo exterior com o uso de interfaces físicas (dispositivos de entrada e saída).');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 3º Ano', 'EF03CO07', 'Utilizar diferentes navegadores e ferramentas de busca para pesquisar e acessar informações.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 3º Ano', 'EF03CO08', 'Usar ferramentas computacionais em situações didáticas para se expressar em diferentes formatos digitais.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 3º Ano', 'EF03CO09', 'Reconhecer o potencial impacto do compartilhamento de informações pessoais ou de seus pares em meio digital.');

-- ENSINO FUNDAMENTAL I - 4º ANO
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 4º Ano', 'EF04CO01', 'Reconhecer objetos do mundo real e/ou digital que podem ser representados através de matrizes que estabelecem uma organização na qual cada componente está em uma posição definida por coordenadas, fazendo manipulações simples sobre estas representações.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 4º Ano', 'EF04CO02', 'Reconhecer objetos do mundo real e/ou digital que podem ser representados através de registros que estabelecem uma organização na qual cada componente é identificado por um nome, fazendo manipulações sobre estas representações.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 4º Ano', 'EF04CO03', 'Criar e simular algoritmos representados em linguagem oral, escrita ou pictográfica, que incluam sequências e repetições simples e aninhadas (iterações definidas e indefinidas), para resolver problemas de forma independente e em colaboração.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 4º Ano', 'EF04CO04', 'Entender que para guardar, manipular e transmitir dados deve-se codificá-los de alguma forma que seja compreendida pela máquina (formato digital).');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 4º Ano', 'EF04CO05', 'Codificar diferentes informações para representação em computador (binária, ASCII, atributos de pixel, como RGB etc.).');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 4º Ano', 'EF04CO06', 'Usar diferentes ferramentas computacionais para criação de conteúdo (textos, apresentações, vídeos etc.).');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 4º Ano', 'EF04CO07', 'Demonstrar postura ética nas atividades de coleta, transferência, guarda e uso de dados.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 4º Ano', 'EF04CO08', 'Reconhecer a importância de verificar a confiabilidade das fontes de informações obtidas na Internet.');

-- ENSINO FUNDAMENTAL I - 5º ANO
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 5º Ano', 'EF05CO01', 'Reconhecer objetos do mundo real e/ou digital que podem ser representados através de listas que estabelecem uma organização na qual há um número variável de itens dispostos em sequência, fazendo manipulações simples sobre estas representações.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 5º Ano', 'EF05CO02', 'Reconhecer objetos do mundo real e digital que podem ser representados através de grafos que estabelecem uma organização com uma quantidade variável de vértices conectados por arestas, fazendo manipulações simples sobre estas representações.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 5º Ano', 'EF05CO03', 'Realizar operações de negação, conjunção e disjunção sobre sentenças lógicas e valores ''verdadeiro'' e ''falso''.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 5º Ano', 'EF05CO04', 'Criar e simular algoritmos representados em linguagem oral, escrita ou pictográfica, que incluam sequências, repetições e seleções condicionais para resolver problemas de forma independente e em colaboração.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 5º Ano', 'EF05CO05', 'Identificar os componentes principais de um computador (dispositivos de entrada/saída, processadores e armazenamento).');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 5º Ano', 'EF05CO06', 'Reconhecer que os dados podem ser armazenados em um dispositivo local ou remoto.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 5º Ano', 'EF05CO07', 'Reconhecer a necessidade de um sistema operacional para a execução de programas e gerenciamento do hardware.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 5º Ano', 'EF05CO08', 'Acessar as informações na Internet de forma crítica para distinguir os conteúdos confiáveis de não confiáveis.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 5º Ano', 'EF05CO09', 'Usar informações considerando aplicações e limites dos direitos autorais em diferentes mídias digitais.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 5º Ano', 'EF05CO10', 'Expressar-se crítica e criativamente na compreensão das mudanças tecnológicas no mundo do trabalho e sobre a evolução da sociedade.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 5º Ano', 'EF05CO11', 'Identificar a adequação de diferentes tecnologias computacionais na resolução de problemas.');

-- ENSINO FUNDAMENTAL I - Habilidades Agrupadas (1º ao 5º Ano)
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 1º ao 5º Ano', 'EF15CO01', 'Identificar as principais formas de organizar e representar a informação de maneira estruturada (matrizes, registros, listas e grafos) ou não estruturada (números, palavras, valores verdade).');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 1º ao 5º Ano', 'EF15CO02', 'Construir e simular algoritmos, de forma independente ou em colaboração, que resolvam problemas simples e do cotidiano com uso de sequências, seleções condicionais e repetições de instruções.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 1º ao 5º Ano', 'EF15CO03', 'Realizar operações de negação, conjunção e disjunção sobre sentenças lógicas e valores ''verdadeiro'' e ''falso''.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 1º ao 5º Ano', 'EF15CO04', 'Aplicar a estratégia de decomposição para resolver problemas complexos, dividindo esse problema em partes menores, resolvendo-as e combinando suas soluções.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 1º ao 5º Ano', 'EF15CO05', 'Codificar a informação de diferentes formas, entendendo a importância desta codificação para o armazenamento, manipulação e transmissão em dispositivos computacionais.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 1º ao 5º Ano', 'EF15CO06', 'Conhecer os componentes básicos de dispositivos computacionais, entendendo os princípios de seu funcionamento.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 1º ao 5º Ano', 'EF15CO07', 'Conhecer o conceito de Sistema Operacional e sua importância na integração entre software e hardware.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 1º ao 5º Ano', 'EF15CO08', 'Reconhecer e utilizar tecnologias computacionais para pesquisar e acessar informações, expressar-se crítica e criativamente e resolver problemas.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental I - 1º ao 5º Ano', 'EF15CO09', 'Entender que as tecnologias devem ser utilizadas de maneira segura, ética e responsável, respeitando direitos autorais, de imagem e as leis vigentes.');

-- ENSINO FUNDAMENTAL II - 6º Ano
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 6º Ano', 'EF06CO01', 'Classificar informações, agrupando-as em coleções (conjuntos) e associando cada coleção a um ''tipo de dado''.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 6º Ano', 'EF06CO02', 'Elaborar algoritmos que envolvam instruções sequenciais, de repetição e de seleção usando uma linguagem de programação.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 6º Ano', 'EF06CO03', 'Descrever com precisão a solução de um problema, construindo o programa que implementa a solução descrita.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 6º Ano', 'EF06CO04', 'Construir soluções de problemas usando a técnica de decomposição e automatizar tais soluções usando uma linguagem de programação.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 6º Ano', 'EF06CO05', 'Identificar os recursos ou insumos necessários (entradas) para a resolução de problemas, bem como os resultados esperados (saídas), determinando os respectivos tipos de dados, e estabelecendo a definição de problema como uma relação entre entrada e saída.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 6º Ano', 'EF06CO06', 'Comparar diferentes casos particulares (instâncias) de um mesmo problema, identificando as semelhanças e diferenças entre eles, e criar um algoritmo para resolver todos, fazendo uso de variáveis (parâmetros) para permitir o tratamento de todos os casos de forma genérica.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 6º Ano', 'EF06CO07', 'Entender o processo de transmissão de dados, como a informação é quebrada em pedaços, transmitida em pacotes através de múltiplos equipamentos, e reconstruída no destino.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 6º Ano', 'EF06CO08', 'Compreender e utilizar diferentes formas de armazenar, manipular, compactar e recuperar arquivos, documentos e metadados.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 6º Ano', 'EF06CO09', 'Apresentar conduta e linguagem apropriadas ao se comunicar em ambiente digital, considerando a ética e o respeito.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 6º Ano', 'EF06CO10', 'Analisar o consumo de tecnologia na sociedade, compreendendo criticamente o caminho da produção dos recursos bem como aspectos ligados à obsolescência e a sustentabilidade.');

-- ENSINO FUNDAMENTAL II - 7º Ano
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 7º Ano', 'EF07CO01', 'Criar soluções de problemas para os quais seja adequado o uso de registros e matrizes unidimensionais para descrever suas informações e automatizá-las usando uma linguagem de programação.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 7º Ano', 'EF07CO02', 'Analisar programas para detectar e remover erros, ampliando a confiança na sua correção.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 7º Ano', 'EF07CO03', 'Construir soluções computacionais de problemas de diferentes áreas do conhecimento, de forma individual e colaborativa, selecionando as estruturas de dados e técnicas adequadas, aperfeiçoando e articulando saberes escolares.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 7º Ano', 'EF07CO04', 'Explorar propriedades básicas de grafos.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 7º Ano', 'EF07CO05', 'Criar algoritmos fazendo uso da decomposição e do reúso no processo de solução de forma colaborativa e cooperativa e automatizá-los usando uma linguagem de programação.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 7º Ano', 'EF07CO06', 'Compreender o papel de protocolos para a transmissão de dados.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 7º Ano', 'EF07CO07', 'Identificar problemas de segurança cibernética e experimentar formas de proteção.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 7º Ano', 'EF07CO08', 'Demonstrar empatia sobre opiniões divergentes na web.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 7º Ano', 'EF07CO09', 'Reconhecer e debater sobre cyberbullying.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 7º Ano', 'EF07CO10', 'Identificar os impactos ambientais do descarte de peças de computadores e eletrônicos, bem como sua relação com a sustentabilidade.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 7º Ano', 'EF07CO11', 'Criar, documentar e publicar, de forma individual ou colaborativa, produtos (vídeos, podcasts, web sites) usando recursos de tecnologia.');

-- ENSINO FUNDAMENTAL II - 8º Ano
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 8º Ano', 'EF08CO01', 'Criar soluções de problemas para os quais seja adequado o uso de recursão como uma técnica de resolver o problema.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 8º Ano', 'EF08CO02', 'Criar soluções de problemas para os quais seja adequado o uso de listas para descrever suas informações e automatizá-las usando uma linguagem de programação, empregando ou não a recursão como uma técnica de resolver o problema.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 8º Ano', 'EF08CO03', 'Utilizar algoritmos clássicos de manipulação sobre listas.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 8º Ano', 'EF08CO04', 'Construir soluções computacionais de problemas de diferentes áreas do conhecimento, de forma individual e colaborativa, selecionando as estruturas de dados e técnicas adequadas, aperfeiçoando e articulando saberes escolares.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 8º Ano', 'EF08CO05', 'Compreender os conceitos de paralelismo, concorrência e armazenamento/processamento distribuídos.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 8º Ano', 'EF08CO06', 'Entender como é a estrutura e funcionamento da internet.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 8º Ano', 'EF08CO07', 'Compartilhar informações por meio de redes sociais, compreendendo a sua dinâmica de funcionamento, de forma responsável e avaliando sua confiabilidade, considerando o respeito e a ética.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 8º Ano', 'EF08CO08', 'Distinguir os tipos de dados pessoais que são solicitados em espaços digitais e os riscos associados.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 8º Ano', 'EF08CO09', 'Analisar criticamente as políticas de termos de uso das redes sociais e demais plataformas.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 8º Ano', 'EF08CO10', 'Discutir questões sobre segurança e privacidade relacionadas ao uso dos ambientes virtuais.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 8º Ano', 'EF08CO11', 'Avaliar a precisão, relevância, adequação, abrangência e vieses que ocorrem em fontes de informação eletrônica.');

-- ENSINO FUNDAMENTAL II - 9º Ano
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 9º Ano', 'EF09CO01', 'Criar soluções de problemas para os quais seja adequado o uso de árvores e grafos para descrever suas informações e automatizá-las usando uma linguagem de programação.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 9º Ano', 'EF09CO02', 'Construir soluções computacionais de problemas de diferentes áreas do conhecimento, de forma individual e colaborativa, selecionando as estruturas de dados e técnicas adequadas, aperfeiçoando e articulando saberes escolares.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 9º Ano', 'EF09CO03', 'Usar autômatos para descrever comportamentos de forma abstrata automatizando-os através de uma linguagem de programação baseada em eventos.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 9º Ano', 'EF09CO04', 'Compreender o funcionamento de malwares e outros ataques cibernéticos.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 9º Ano', 'EF09CO05', 'Analisar técnicas de criptografia para armazenamento e transmissão de dados.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 9º Ano', 'EF09CO06', 'Analisar problemas sociais de sua cidade e estado a partir de ambientes digitais, propondo soluções.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 9º Ano', 'EF09CO07', 'Identificar os componentes e o fluxo de dados em uma arquitetura de computação, bem como o processo de comunicação e o papel das redes de computadores.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 9º Ano', 'EF09CO08', 'Reconhecer diferentes tipos de crimes e infrações em ambientes digitais.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 9º Ano', 'EF09CO09', 'Refletir sobre o uso de tecnologias e sobre os dilemas éticos associados, avaliando as suas implicações na sociedade, nos processos de trabalho e na vida cotidiana.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 9º Ano', 'EF09CO10', 'Interpretar textos informativos e opinativos na Internet, a partir da avaliação de sua veracidade e credibilidade.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 9º Ano', 'EF09CO11', 'Compreender os conceitos de privacidade e segurança, aplicando boas práticas de proteção de seus dados e de seus pares.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 9º Ano', 'EF09CO12', 'Aprender sobre o uso de tecnologia na construção de um mundo mais justo e sustentável.');

-- Continuação dos Inserts para o Ensino Fundamental II - 9º Ano
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 9º Ano', 'EF09CO07', 'Aplicar conhecimentos computacionais para propor soluções aos desafios da atualidade do ser humano em qualquer área.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 9º Ano', 'EF09CO08', 'Discutir como a distribuição desigual de recursos de computação em uma economia global levanta questões de equidade, acesso e poder.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 9º Ano', 'EF09CO09', 'Criar ou utilizar conteúdo em meio digital, compreendendo questões éticas relacionadas a direitos autorais e de uso de imagem.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 9º Ano', 'EF09CO10', 'Avaliar a veracidade, credibilidade e relevância da informação em seus diferentes formatos, sendo capaz de identificar o propósito pelo qual foi disseminada.');

-- Habilidades Agrupadas (6º ao 9º Ano)
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 6º ao 9º Ano', 'EF69CO01', 'Classificar informações, agrupando-as em coleções (conjuntos) e associando cada coleção a um ''tipo de dado''.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 6º ao 9º Ano', 'EF69CO02', 'Elaborar algoritmos que envolvam instruções sequenciais, de repetição e de seleção usando uma linguagem de programação.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 6º ao 9º Ano', 'EF69CO03', 'Descrever com precisão a solução de um problema, construindo o programa que implementa a solução descrita.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 6º ao 9º Ano', 'EF69CO04', 'Construir soluções de problemas usando a técnica de decomposição e automatizar tais soluções usando uma linguagem de programação.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 6º ao 9º Ano', 'EF69CO05', 'Identificar os recursos ou insumos necessários (entradas) para a resolução de problemas, bem como os resultados esperados (saídas), determinando os respectivos tipos de dados, e estabelecendo a definição de problema como uma relação entre entrada e saída.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 6º ao 9º Ano', 'EF69CO06', 'Comparar diferentes casos particulares (instâncias) de um mesmo problema, identificando as semelhanças e diferenças entre eles, e criar um algoritmo para resolver todos, fazendo uso de variáveis (parâmetros) para permitir o tratamento de todos os casos de forma genérica.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 6º ao 9º Ano', 'EF69CO07', 'Entender o processo de transmissão de dados, como a informação é quebrada em pedaços, transmitida em pacotes através de múltiplos equipamentos, e reconstruída no destino.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 6º ao 9º Ano', 'EF69CO08', 'Compreender e utilizar diferentes formas de armazenar, manipular, compactar e recuperar arquivos, documentos e metadados.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 6º ao 9º Ano', 'EF69CO09', 'Compreender os conceitos de paralelismo, concorrência e armazenamento/processamento distribuídos.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 6º ao 9º Ano', 'EF69CO10', 'Entender como é a estrutura e funcionamento da internet.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 6º ao 9º Ano', 'EF69CO11', 'Apresentar conduta e linguagem apropriadas ao se comunicar em ambiente digital, considerando a ética e o respeito.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Fundamental II - 6º ao 9º Ano', 'EF69CO12', 'Analisar o consumo de tecnologia na sociedade, compreendendo criticamente o caminho da produção dos recursos bem como aspectos ligados à obsolescência e a sustentabilidade.');

-- Ensino Médio
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Médio', 'EM13CO01', 'Explorar e construir a solução de problemas por meio da reutilização de partes de soluções existentes.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Médio', 'EM13CO02', 'Explorar e construir a solução de problemas por meio de refinamentos, utilizando diversos níveis de abstração desde a especificação até a implementação.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Médio', 'EM13CO03', 'Identificar o comportamento dos algoritmos no que diz respeito ao consumo de recursos como tempo de execução, espaço de memória e energia, entre outros.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Médio', 'EM13CO04', 'Reconhecer o conceito de metaprogramação como uma forma de generalização na construção de programas, permitindo que algoritmos sejam entrada ou saída para outros algoritmos.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Médio', 'EM13CO05', 'Identificar os limites da Computação para diferenciar o que pode ou não ser automatizado, buscando uma compreensão mais ampla dos limites dos processos mentais envolvidos na resolução de problemas.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Médio', 'EM13CO06', 'Avaliar software levando em consideração diferentes características e métricas associadas.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Médio', 'EM13CO07', 'Compreender as diferentes tecnologias, bem como equipamentos, protocolos e serviços envolvidos no funcionamento de redes de computadores, identificando suas possibilidades de escala e confiabilidade.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Médio', 'EM13CO08', 'Entender como mudanças na tecnologia afetam a segurança, incluindo novas maneiras de preservar sua privacidade e dados pessoais on-line, reportando suspeitas e buscando ajuda em situações de risco.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Médio', 'EM13CO09', 'Identificar tecnologias digitais, sua presença e formas de uso, nas diferentes atividades no mundo do trabalho.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Médio', 'EM13CO10', 'Conhecer os fundamentos da Inteligência Artificial, comparando-a com a inteligência humana, analisando suas potencialidades, riscos e limites.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Médio', 'EM13CO11', 'Criar e explorar modelos computacionais simples para simular e fazer previsões, identificando sua importância no desenvolvimento científico.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Médio', 'EM13CO12', 'Produzir, analisar, gerir e compartilhar informações a partir de dados, utilizando princípios de ciência de dados.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Médio', 'EM13CO13', 'Analisar e utilizar as diferentes formas de representação e consulta a dados em formato digital para pesquisas científicas.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Médio', 'EM13CO14', 'Avaliar a confiabilidade das informações encontradas em meio digital, investigando seus modos de construção e considerando a autoria, a estrutura e o propósito da mensagem.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Médio', 'EM13CO15', 'Analisar a interação entre usuários e artefatos computacionais, abordando aspectos da experiência do usuário e promovendo reflexão sobre a qualidade do uso dos artefatos nas esferas do trabalho, do lazer e do estudo.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Médio', 'EM13CO16', 'Desenvolver projetos com robótica, utilizando artefatos físicos ou simuladores.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Médio', 'EM13CO17', 'Construir redes virtuais de interação e colaboração, favorecendo o desenvolvimento de projetos de forma segura, legal e ética.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Médio', 'EM13CO18', 'Planejar e gerenciar projetos integrados às áreas de conhecimento de forma colaborativa, solucionando problemas, usando diversos artefatos computacionais.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Médio', 'EM13CO19', 'Expor, argumentar e negociar propostas, produtos e serviços, utilizando diferentes mídias e ferramentas digitais.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Médio', 'EM13CO20', 'Criar conteúdos, disponibilizando-os em ambientes virtuais para publicação e compartilhamento, avaliando a confiabilidade e as consequências da disseminação dessas informações.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Médio', 'EM13CO21', 'Comunicar ideias complexas de forma clara por meio de objetos digitais como mapas conceituais, infográficos, hipertextos e outros.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Médio', 'EM13CO22', 'Produzir e publicar conteúdo como textos, imagens, áudios, vídeos e suas associações, bem como ferramentas para sua integração, organização e apresentação, utilizando diferentes mídias digitais.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Médio', 'EM13CO23', 'Analisar criticamente as experiências em comunidades virtuais e as relações advindas da interação e comunicação com outras pessoas, bem como seus impactos na sociedade.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Médio', 'EM13CO24', 'Identificar e reconhecer como as redes sociais e artefatos computacionais em geral interferem na saúde física e mental de seus usuários.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Médio', 'EM13CO25', 'Dialogar em ambientes virtuais com segurança e respeito às diferenças culturais e pessoais, reconhecendo e denunciando atitudes abusivas.');
INSERT INTO habilidades (etapa_educacional, codigo_habilidade, descricao) VALUES ('Ensino Médio', 'EM13CO26', 'Aplicar os conceitos e pressupostos do direito digital em sua conduta e experiências com o cotidiano da cultura digital, bem como na produção e uso de artefatos computacionais.');